(() => {
'use strict';
const API='https://xyuwqccmqggoctprbhzb.supabase.co/rest/v1',KEY='sb_publishable_RHnLnO4J-PdXnPhLQUHeXg_9vJjjzCx';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const session=()=>{try{return JSON.parse(localStorage.getItem('dropfly-supabase-session')||'null')}catch{return null}};
const user=()=>session()?.user||null,role=()=>user()?.app_metadata?.role||user()?.user_metadata?.role||($('.admin')?'admin':'merchant');
async function api(path,query='',method='GET',body){const s=session();if(!s?.access_token)throw Error('انتهت الجلسة، سجل الدخول مجدداً');const res=await fetch(API+'/'+path+(query?'?'+query:''),{method,headers:{apikey:KEY,Authorization:'Bearer '+s.access_token,'Content-Type':'application/json',Prefer:method==='POST'?'return=representation':'return=minimal'},body:body===undefined?undefined:JSON.stringify(body)});const txt=await res.text();let data;try{data=txt?JSON.parse(txt):[]}catch{data=[]}if(!res.ok)throw Error(data.message||data.details||'تعذر إكمال العملية');return data}
const date=v=>v?new Date(v).toLocaleString('ar-IQ',{dateStyle:'medium',timeStyle:'short'}):'—',cash=v=>Number(v||0).toLocaleString('en-US')+' د.ع';
function el(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!=null)n.textContent=String(text);return n}
function sound(title,body,tag){try{if(sessionStorage.getItem('df-sound-enabled')==='1'&&window.AudioContext){const c=new AudioContext(),o=c.createOscillator(),g=c.createGain();o.type='sine';o.frequency.setValueAtTime(880,c.currentTime);o.frequency.setValueAtTime(1174,c.currentTime+.12);g.gain.setValueAtTime(.0001,c.currentTime);g.gain.exponentialRampToValueAtTime(.14,c.currentTime+.02);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+.42);o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.44)}}catch{}try{if(window.Notification?.permission==='granted')new Notification(title,{body,tag})}catch{}}
function soundButtons(){[['.admin-header','df-sound-toggle'],['.merchant-app .header-actions','df-merchant-sound-toggle']].forEach(([selector,id])=>{const host=$(selector);if(!host||$('#'+id))return;const b=el('button','df-sound-toggle',sessionStorage.getItem('df-sound-enabled')==='1'?'🔔 الصوت مفعل':'🔕 تفعيل صوت التنبيهات');b.id=id;b.type='button';b.onclick=async()=>{sessionStorage.setItem('df-sound-enabled','1');try{if(Notification?.permission==='default')await Notification.requestPermission()}catch{}sound('اختبار التنبيه','تم تفعيل صوت التنبيهات','df-test');b.textContent='🔔 الصوت مفعل'};host.append(b)})}
let seen=new Set(),primed=false,poll=null;
async function pollNotices(){const u=user();if(!session()?.access_token||!u?.id)return;const q=role()==='admin'?'recipient_role=eq.admin':'recipient_id=eq.'+encodeURIComponent(u.id);try{const rows=await api('wholesale_notifications','select=id,title,body,message,kind&'+q+'&order=created_at.desc&limit=80');const next=new Set(rows.map(x=>x.id));if(primed)rows.forEach(n=>{if(!seen.has(n.id)&&(role()!=='admin'||n.kind!=='support'))sound(n.title||'إشعار جديد',n.body||n.message||'لديك تحديث جديد',n.id)});seen=next;primed=true}catch{}}
function startPoll(){if(poll)clearInterval(poll);seen=new Set();primed=false;pollNotices();poll=setInterval(pollNotices,12000)}
async function pendingPayments(){const ledger=$('.merchant-app .ledger');if(!ledger||ledger.dataset.pendingLoaded)return;ledger.dataset.pendingLoaded='yes';try{const id=user()?.id;if(!id)return;const rows=await api('wholesale_payout_requests','select=id,requested_amount,requested_at,created_at&merchant_id=eq.'+encodeURIComponent(id)+'&status=eq.pending&order=requested_at.desc&limit=10');rows.forEach(r=>{const a=el('article','df-payout-pending');a.append(el('span','','◷'));const d=el('div','');d.append(el('b','','طلب تسديد قيد الانتظار'),el('small','','تاريخ الطلب: '+date(r.requested_at||r.created_at)));a.append(d,el('strong','',cash(r.requested_amount)));ledger.append(a)})}catch{delete ledger.dataset.pendingLoaded}}
let chat=null,chatPoll=null,ticketPoll=null,seenMessages=new Set(),messagesPrimed=false;
function closeChat(){if(chatPoll)clearInterval(chatPoll);chatPoll=null;chat?.remove();chat=null}
async function openChat(ticket,name){closeChat();chat=el('div','df-support-backdrop');const panel=el('section','df-support-chat'),head=el('header','');head.append(el('b','',name+' • '+(ticket.subject||'الدعم')));const close=el('button','','×');close.onclick=closeChat;head.append(close);
localStorage.setItem('df-opened-'+ticket.id,new Date().toISOString());api('rpc/wholesale_mark_ticket_open','','POST',{p_ticket_id:ticket.id}).catch(()=>api('wholesale_support_tickets','id=eq.'+encodeURIComponent(ticket.id),'PATCH',{status:'in_progress'}).catch(()=>{}));
const meta=el('p','df-support-meta','تاريخ الفتح: '+date(ticket.admin_opened_at||localStorage.getItem('df-opened-'+ticket.id)||ticket.created_at)),list=el('div','df-support-messages'),form=el('form','df-support-form'),input=el('textarea');input.maxLength=5000;input.placeholder='اكتب ردك للنشاط التجاري';const send=el('button','','إرسال الرد');send.type='submit';form.append(input,send);panel.append(head,meta,list,form);chat.append(panel);document.body.append(chat);chat.onclick=e=>{if(e.target===chat)closeChat()};let sig='';
async function refresh(){if(!chat?.isConnected)return;const rows=await api('wholesale_support_messages','select=id,sender_id,body,created_at,deleted_at&ticket_id=eq.'+encodeURIComponent(ticket.id)+'&order=created_at.asc'),signature=JSON.stringify(rows.map(m=>[m.id,m.body,m.deleted_at]));if(signature!==sig){sig=signature;list.replaceChildren();rows.forEach(m=>{const own=m.sender_id===user()?.id,b=el('article','df-message '+(own?'df-mine':'df-theirs'));b.append(el('b','',own?'الإدارة':'النشاط التجاري'),el('p','',m.deleted_at?'رسالة محذوفة':m.body||''),el('time','',date(m.created_at)));list.append(b)});list.scrollTop=list.scrollHeight}const expired=ticket.status==='closed'||(ticket.expires_at&&Date.now()>=Date.parse(ticket.expires_at));input.disabled=send.disabled=!!expired;meta.textContent=expired?'انتهت الدردشة بعد 24 ساعة • تاريخ الفتح: '+date(ticket.admin_opened_at||localStorage.getItem('df-opened-'+ticket.id)):'تاريخ الفتح: '+date(ticket.admin_opened_at||localStorage.getItem('df-opened-'+ticket.id))+' • آخر رد: '+date(rows.at(-1)?.created_at||ticket.created_at)}
form.onsubmit=async e=>{e.preventDefault();const body=input.value.trim();if(!body)return;send.disabled=true;try{await api('wholesale_support_messages','','POST',{ticket_id:ticket.id,sender_id:user()?.id,body});input.value='';sig='';await refresh()}catch(err){alert(err.message)}finally{send.disabled=false}};
try{await refresh()}catch(e){list.append(el('p','',e.message))}chatPoll=setInterval(()=>refresh().catch(()=>{}),3500)}
async function tickets(list,count){const fields='id,order_id,merchant_id,subject,status,created_at,expires_at,admin_opened_at,last_admin_reply_at,last_merchant_reply_at';let rows;try{rows=await api('wholesale_support_tickets','select='+fields+'&order=created_at.desc&limit=150')}catch{rows=await api('wholesale_support_tickets','select=id,order_id,merchant_id,subject,status,created_at,expires_at&order=created_at.desc&limit=150')}
try{const recent=await api('wholesale_support_messages','select=id,sender_id,created_at&created_at=gte.'+encodeURIComponent(new Date(Date.now()-86400000).toISOString())+'&order=created_at.desc&limit=300');if(messagesPrimed)recent.forEach(m=>{if(m.sender_id!==user()?.id&&!seenMessages.has(m.id))sound('رسالة دعم جديدة','وصلت رسالة من نشاط تجاري','support-'+m.id)});seenMessages=new Set(recent.map(m=>m.id));messagesPrimed=true}catch{}
const ids=[...new Set(rows.map(t=>t.merchant_id).filter(Boolean))],profiles=ids.length?await api('wholesale_profiles','select=id,full_name,business_name&id=in.('+ids.join(',')+')'):[],names=new Map(profiles.map(p=>[p.id,p.business_name||p.full_name]));list.replaceChildren();count.textContent=rows.length+' محادثة';if(!rows.length){list.append(el('p','','لا توجد محادثات دعم حالياً'));return}rows.forEach(t=>{const row=el('article','df-ticket-row'),d=el('div','');d.append(el('b','',names.get(t.merchant_id)||'نشاط تجاري'),el('p','',t.subject||'دردشة دعم'),el('small','','أُنشئت: '+date(t.created_at)+' • آخر تحديث: '+date(t.last_merchant_reply_at||t.last_admin_reply_at||t.created_at)),el('small','df-open-state',(t.admin_opened_at||localStorage.getItem('df-opened-'+t.id))?'فُتحت: '+date(t.admin_opened_at||localStorage.getItem('df-opened-'+t.id)):'لم تُفتح بعد'));const b=el('button','','فتح المحادثة');b.onclick=()=>openChat(t,names.get(t.merchant_id)||'النشاط التجاري');row.append(d,b);list.append(row)})}
function supportPage(){const page=$('.admin-support-page');if(!page)return;$('#df-admin-chat-button')?.remove();let box=$('#df-support-inbox',page);if(!box){box=el('section','df-support-inbox');box.id='df-support-inbox';const h=el('header','');h.append(el('h2','','دردشات الأنشطة التجارية'),el('span','df-ticket-count','جارِ التحميل'));box.append(h,el('div','df-ticket-list'));page.append(box)}if(box.dataset.started)return;box.dataset.started='1';const update=()=>tickets($('.df-ticket-list',box),$('.df-ticket-count',box)).catch(e=>$('.df-ticket-count',box).textContent=e.message);update();if(ticketPoll)clearInterval(ticketPoll);ticketPoll=setInterval(()=>{if($('.admin-support-page'))update()},5000)}
function traders(){const page=$('.admin .users-management'),cards=$('.admin-cards',page);if(!page||!cards)return;if(!$('#df-trader-search',page)){const bar=el('div','df-trader-filter'),input=el('input');input.id='df-trader-search';input.placeholder='بحث بالاسم أو النشاط أو الهاتف';const select=document.createElement('select');[['all','كل المستخدمين'],['تاجر','التجار فقط'],['مشرف','المشرفون فقط']].forEach(([v,l])=>{const o=document.createElement('option');o.value=v;o.textContent=l;select.append(o)});bar.append(input,select);cards.before(bar);const filter=()=>$$(':scope>article',cards).forEach(c=>c.hidden=!c.innerText.toLowerCase().includes(input.value.trim().toLowerCase())||(select.value!=='all'&&!c.innerText.includes(select.value)));input.oninput=filter;select.onchange=filter}
$$('.admin-cards>article:not(.df-bound)',cards).forEach(card=>{card.classList.add('df-bound');card.addEventListener('click',e=>{if(e.target.closest('button,a'))return;traderProfile(card).catch(x=>alert(x.message))})})}
async function traderProfile(card){const phone=$$('p',card).find(x=>x.dir==='ltr')?.textContent.trim(),name=$('h3',card)?.textContent||'',all=await api('wholesale_profiles','select=id,full_name,business_name,phone,created_at&phone=eq.'+encodeURIComponent(phone)+'&limit=20'),p=all.find(x=>x.business_name===name||x.full_name===name)||all[0];if(!p)throw Error('تعذر تحديد حساب التاجر');const [orders,tx]=await Promise.all([api('wholesale_orders','select=id,status,customer_price,product_price,created_at,order_number&merchant_id=eq.'+p.id+'&order=created_at.desc&limit=1500'),api('wholesale_transactions','select=id,amount,title,kind,created_at&merchant_id=eq.'+p.id+'&order=created_at.desc&limit=500')]);const delivered=orders.filter(o=>o.status==='تم التوصيل').length,returned=orders.filter(o=>['راجع','مرتجع','مرتجعة','مرفوض'].includes(o.status)).length,balance=Math.max(0,tx.reduce((a,t)=>a+Number(t.amount||0),0));let pane=$('#df-trader-profile');if(!pane){pane=el('section','df-trader-profile');pane.id='df-trader-profile';cardsAfter(card,pane)}pane.replaceChildren();const h=el('header','');h.append(el('h2','',name+' • الملف المالي'));const x=el('button','','إغلاق');x.onclick=()=>pane.remove();h.append(x);pane.append(h);const stats=el('div','df-trader-stats');[['كل الطلبات',orders.length],['الواصل',delivered],['الراجع',returned],['غير المسدد',cash(balance)],['تاريخ الانضمام',date(p.created_at)]].forEach(v=>{const a=el('article','');a.append(el('small','',v[0]),el('b','',v[1]));stats.append(a)});pane.append(stats,el('h3','','المعاملات المالية'));tx.forEach(t=>{const r=el('div','df-transaction');r.append(el('span','',t.title||t.kind||'معاملة'),el('time','',date(t.created_at)),el('b','',cash(t.amount)));pane.append(r)})}
function cardsAfter(card,pane){const c=card.closest('.admin-cards');c.after(pane)}
function orderTools(){const page=$('.admin .admin-table.admin-full');if(!page)return;$$('.admin-table.admin-full>article:not(.df-actions-added)',page).forEach(card=>{if(card.classList.contains('empty-inline'))return;const id=card.innerText.match(/DF-[\w-]+/)?.[0];if(!id)return;card.classList.add('df-actions-added');const tools=el('div','df-order-tools'),edit=el('button','','تعديل'),del=el('button','','حذف'),status=document.createElement('select');[['','تغيير الحالة'],['قيد الانتظار','قيد الانتظار'],['قيد التجهيز','قيد التجهيز'],['قيد التوصيل','قيد التوصيل'],['تم التوصيل','تم التوصيل'],['راجع','راجع']].forEach(([v,l])=>{const o=document.createElement('option');o.value=v;o.textContent=l;status.append(o)});
edit.onclick=async e=>{e.stopPropagation();const customer=prompt('اسم الزبون');if(customer===null)return;const phone=prompt('هاتف الزبون');if(phone===null)return;const price=prompt('سعر البيع المتفق عليه');if(price===null)return;try{await api('wholesale_orders','order_number=eq.'+encodeURIComponent(id),'PATCH',{customer_name:customer,customer_phone:phone,customer_price:Number(price)});location.reload()}catch(x){alert(x.message)}};
del.onclick=async e=>{e.stopPropagation();if(!confirm('حذف الطلب '+id+' نهائياً؟'))return;try{await api('wholesale_orders','order_number=eq.'+encodeURIComponent(id),'DELETE');location.reload()}catch(x){alert(x.message)}};
status.onchange=async e=>{e.stopPropagation();if(!status.value)return;try{await api('wholesale_orders','order_number=eq.'+encodeURIComponent(id),'PATCH',{status:status.value,status_changed_at:new Date().toISOString()});location.reload()}catch(x){alert(x.message)}};
tools.append(edit,del,status);card.append(tools)})}
function restrictCreate(){const active=$('.admin-header nav button.active')?.textContent||'',ok=active.includes('الرئيسية')||active.includes('الطلبات');$$('.admin .admin-welcome .main-btn').forEach(b=>b.hidden=!ok)}
let scheduled=false;function scan(){scheduled=false;if(!session()?.access_token){if(ticketPoll)clearInterval(ticketPoll);ticketPoll=null;return}if($('.admin')){soundButtons();supportPage();traders();orderTools();restrictCreate()}if($('.merchant-app .ledger'))pendingPayments()}
new MutationObserver(()=>{if(!scheduled){scheduled=true;requestAnimationFrame(scan)}}).observe(document.documentElement,{childList:true,subtree:true,attributes:true,attributeFilter:['class']});
document.addEventListener('click',e=>{if(e.target.closest('.admin-header nav button'))setTimeout(scan,80)});startPoll();scan();window.addEventListener('storage',startPoll);
})();
