(() => {
'use strict';
const API='https://xyuwqccmqggoctprbhzb.supabase.co/rest/v1',KEY='sb_publishable_RHnLnO4J-PdXnPhLQUHeXg_9vJjjzCx';
const VAPID_PUBLIC='BCFsned-7k32oz0PJ7efIhbHakA1_wiQmsebBecfPqbEimnhM2KKWfuC15lfWRUmX2iJo6r4eq6UJ2baYqq8rw0';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const session=()=>{try{return JSON.parse(localStorage.getItem('dropfly-supabase-session')||'null')}catch{return null}};
const user=()=>session()?.user||null,role=()=>user()?.app_metadata?.role||user()?.user_metadata?.role||($('.admin')?'admin':'merchant');
async function api(path,query='',method='GET',body){const s=session();if(!s?.access_token)throw Error('انتهت الجلسة، سجل الدخول مجدداً');const res=await fetch(API+'/'+path+(query?'?'+query:''),{method,headers:{apikey:KEY,Authorization:'Bearer '+s.access_token,'Content-Type':'application/json',Prefer:method==='POST'?'return=representation':'return=minimal'},body:body===undefined?undefined:JSON.stringify(body)});const txt=await res.text();let data;try{data=txt?JSON.parse(txt):[]}catch{data=[]}if(!res.ok)throw Error(data.message||data.details||'تعذر إكمال العملية');return data}
const date=v=>v?new Date(v).toLocaleString('ar-IQ',{dateStyle:'medium',timeStyle:'short'}):'—',cash=v=>Number(v||0).toLocaleString('en-US')+' د.ع';
function el(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!=null)n.textContent=String(text);return n}
function sound(title,body,tag){try{if(sessionStorage.getItem('df-sound-enabled')==='1'&&window.AudioContext){const c=new AudioContext(),o=c.createOscillator(),g=c.createGain();o.type='sine';o.frequency.setValueAtTime(880,c.currentTime);o.frequency.setValueAtTime(1174,c.currentTime+.12);g.gain.setValueAtTime(.0001,c.currentTime);g.gain.exponentialRampToValueAtTime(.14,c.currentTime+.02);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+.42);o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.44)}}catch{}try{if(window.Notification?.permission==='granted')new Notification(title,{body,tag})}catch{}}
function soundButtons(){const host=$('.admin-header');if(!host||$('#df-sound-toggle'))return;const b=el('button','df-sound-toggle');b.id='df-sound-toggle';b.type='button';const update=()=>b.textContent=sessionStorage.getItem('df-sound-enabled')==='1'?'🔊 الصوت مفعل':'🔇 تفعيل صوت التنبيهات';update();b.onclick=()=>{sessionStorage.setItem('df-sound-enabled',sessionStorage.getItem('df-sound-enabled')==='1'?'0':'1');update()};host.append(b)}
function vapidBytes(value){const raw=atob(value.replace(/-/g,'+').replace(/_/g,'/'));return Uint8Array.from(raw,c=>c.charCodeAt(0))}
async function registerPush(){if(!('serviceWorker'in navigator)||!('PushManager'in window)||!('Notification'in window))throw Error('المتصفح لا يدعم إشعارات الهاتف');const permission=await Notification.requestPermission();if(permission!=='granted')throw Error('اسمح بالإشعارات من إعدادات المتصفح');const registration=await navigator.serviceWorker.ready;let sub=await registration.pushManager.getSubscription();if(!sub)sub=await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:vapidBytes(VAPID_PUBLIC)});const u=user(),s=session();if(!u?.id||!s?.access_token)throw Error('سجل الدخول ثم حاول مجدداً');const keys=sub.toJSON().keys||{};const response=await fetch(API+'/wholesale_push_subscriptions?on_conflict=endpoint',{method:'POST',headers:{apikey:KEY,Authorization:'Bearer '+s.access_token,'Content-Type':'application/json',Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({user_id:u.id,recipient_role:role()==='admin'?'admin':'merchant',endpoint:sub.endpoint,p256dh:keys.p256dh,auth:keys.auth})});if(!response.ok)throw Error('تعذر حفظ إعداد الإشعارات')}
function pushButton(){if(!VAPID_PUBLIC||VAPID_PUBLIC.startsWith('__'))return;const host=$('.admin-header');if(!host||$('#df-admin-push'))return;const b=el('button','df-push-toggle','🔔 تفعيل إشعارات الهاتف');b.id='df-admin-push';b.type='button';b.onclick=async()=>{b.disabled=true;try{await registerPush();b.textContent='🔔 إشعارات الهاتف مفعّلة'}catch(e){alert(e.message||'تعذر تفعيل الإشعارات')}finally{b.disabled=false}};host.append(b)}
function merchantNotificationControls(){const host=$('.merchant-app .header-actions');if(!host||$('#df-merchant-notification-settings',host))return;const wrap=el('div','df-notification-settings');wrap.id='df-merchant-notification-settings';const trigger=el('button','df-notification-trigger','⚙');trigger.type='button';trigger.title='إعدادات الإشعارات';trigger.setAttribute('aria-label','إعدادات الإشعارات');trigger.setAttribute('aria-expanded','false');const menu=el('div','df-notification-menu');menu.hidden=true;menu.append(el('strong','','إعدادات الإشعارات'));const soundButton=el('button','df-notification-option'),push=el('button','df-notification-option');soundButton.type=push.type='button';const updateSound=()=>{const on=sessionStorage.getItem('df-sound-enabled')==='1';soundButton.textContent=on?'🔊  صوت التنبيهات مفعّل':'🔇  تفعيل صوت التنبيهات';soundButton.setAttribute('aria-pressed',String(on))};updateSound();soundButton.onclick=()=>{sessionStorage.setItem('df-sound-enabled',sessionStorage.getItem('df-sound-enabled')==='1'?'0':'1');updateSound()};push.textContent='📱  تفعيل إشعارات الهاتف';push.onclick=async()=>{push.disabled=true;push.textContent='جارِ تفعيل إشعارات الهاتف…';try{await registerPush();push.textContent='✓  إشعارات الهاتف مفعّلة';push.classList.add('is-active')}catch(e){push.textContent='📱  تفعيل إشعارات الهاتف';message.textContent=e.message||'تعذر تفعيل الإشعارات'}finally{push.disabled=false}};const message=el('small','df-notification-hint','تصل الإشعارات حتى بعد إغلاق الموقع عند تفعيلها');menu.append(soundButton,push,message);wrap.append(trigger,menu);host.insertBefore(wrap,host.querySelector('.logout'));trigger.onclick=e=>{e.stopPropagation();menu.hidden=!menu.hidden;trigger.setAttribute('aria-expanded',String(!menu.hidden))}}
document.addEventListener('click',e=>{const wrap=$('#df-merchant-notification-settings');if(wrap&&!wrap.contains(e.target)){const menu=$('.df-notification-menu',wrap);menu.hidden=true;$('.df-notification-trigger',wrap).setAttribute('aria-expanded','false')}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){const menu=$('#df-merchant-notification-settings .df-notification-menu');if(menu&&!menu.hidden){menu.hidden=true;$('#df-merchant-notification-settings .df-notification-trigger')?.focus()}}});
let seen=new Set(),primed=false,poll=null;
async function pollNotices(){const u=user();if(!session()?.access_token||!u?.id)return;const q=role()==='admin'?'recipient_role=eq.admin':'recipient_id=eq.'+encodeURIComponent(u.id);try{const rows=await api('wholesale_notifications','select=id,title,body,message,kind&'+q+'&order=created_at.desc&limit=80');const next=new Set(rows.map(x=>x.id));if(primed)rows.forEach(n=>{if(!seen.has(n.id)&&(role()!=='admin'||n.kind!=='support'))sound(n.title||'إشعار جديد',n.body||n.message||'لديك تحديث جديد',n.id)});seen=next;primed=true}catch{}}
function startPoll(){if(poll)clearInterval(poll);seen=new Set();primed=false;pollNotices();poll=setInterval(pollNotices,12000)}
async function pendingPayments(){const ledger=$('.merchant-app .ledger');if(!ledger||ledger.dataset.pendingLoaded)return;ledger.dataset.pendingLoaded='yes';try{const id=user()?.id;if(!id)return;const rows=await api('wholesale_payout_requests','select=id,requested_amount,requested_at&merchant_id=eq.'+encodeURIComponent(id)+'&status=eq.pending&order=requested_at.desc&limit=10');rows.forEach(r=>{const a=el('article','df-payout-pending');a.append(el('span','','◷'));const d=el('div','');d.append(el('b','','طلب تسديد قيد الانتظار'),el('small','','تاريخ الطلب: '+date(r.requested_at)));a.append(d,el('strong','',cash(r.requested_amount)));ledger.append(a)})}catch{delete ledger.dataset.pendingLoaded}}
let chat=null,chatPoll=null,ticketPoll=null,seenMessages=new Set(),messagesPrimed=false;
function closeChat(){if(chatPoll)clearInterval(chatPoll);chatPoll=null;chat?.remove();chat=null}
async function openChat(ticket,name){closeChat();chat=el('div','df-support-backdrop');const panel=el('section','df-support-chat'),head=el('header','');head.append(el('b','',name+' • '+(ticket.subject||'الدعم')));const close=el('button','','×');close.onclick=closeChat;head.append(close);
localStorage.setItem('df-opened-'+ticket.id,new Date().toISOString());api('rpc/wholesale_mark_ticket_open','','POST',{p_ticket_id:ticket.id}).catch(()=>api('wholesale_support_tickets','id=eq.'+encodeURIComponent(ticket.id),'PATCH',{status:'in_progress'}).catch(()=>{}));api('wholesale_notifications','kind=eq.support&recipient_role=eq.admin&entity_id=eq.'+encodeURIComponent(ticket.order_id||ticket.id),'PATCH',{is_read:true}).catch(()=>{});
const meta=el('p','df-support-meta','تاريخ الفتح: '+date(ticket.admin_opened_at||localStorage.getItem('df-opened-'+ticket.id)||ticket.created_at)),list=el('div','df-support-messages'),form=el('form','df-support-form'),input=el('textarea');input.maxLength=5000;input.placeholder='اكتب ردك للنشاط التجاري';const send=el('button','','إرسال الرد');send.type='submit';form.append(input,send);panel.append(head,meta,list,form);chat.append(panel);document.body.append(chat);chat.onclick=e=>{if(e.target===chat)closeChat()};let sig='';
async function refresh(){if(!chat?.isConnected)return;const rows=await api('wholesale_support_messages','select=id,sender_id,body,created_at,deleted_at&ticket_id=eq.'+encodeURIComponent(ticket.id)+'&order=created_at.asc'),signature=JSON.stringify(rows.map(m=>[m.id,m.body,m.deleted_at]));if(signature!==sig){sig=signature;list.replaceChildren();rows.forEach(m=>{const own=m.sender_id===user()?.id,b=el('article','df-message '+(own?'df-mine':'df-theirs'));b.append(el('b','',own?'الإدارة':'النشاط التجاري'),el('p','',m.deleted_at?'رسالة محذوفة':m.body||''),el('time','',date(m.created_at)));list.append(b)});list.scrollTop=list.scrollHeight}const expired=ticket.status==='closed'||(ticket.expires_at&&Date.now()>=Date.parse(ticket.expires_at));input.disabled=send.disabled=!!expired;meta.textContent=expired?'انتهت الدردشة بعد 24 ساعة • تاريخ الفتح: '+date(ticket.admin_opened_at||localStorage.getItem('df-opened-'+ticket.id)):'تاريخ الفتح: '+date(ticket.admin_opened_at||localStorage.getItem('df-opened-'+ticket.id))+' • آخر رد: '+date(rows.at(-1)?.created_at||ticket.created_at)}
form.onsubmit=async e=>{e.preventDefault();const body=input.value.trim();if(!body)return;send.disabled=true;try{await api('wholesale_support_messages','','POST',{ticket_id:ticket.id,sender_id:user()?.id,body});input.value='';sig='';await refresh()}catch(err){alert(err.message)}finally{send.disabled=false}};
try{await refresh()}catch(e){list.append(el('p','',e.message))}chatPoll=setInterval(()=>refresh().catch(()=>{}),3500)}
async function tickets(list,count){const fields='id,order_id,merchant_id,subject,status,created_at,expires_at,admin_opened_at,last_admin_reply_at,last_merchant_reply_at';let rows;try{rows=await api('wholesale_support_tickets','select='+fields+'&order=created_at.desc&limit=150')}catch{rows=await api('wholesale_support_tickets','select=id,order_id,merchant_id,subject,status,created_at,expires_at&order=created_at.desc&limit=150')}
let unread=new Map;try{const notices=await api('wholesale_notifications','select=entity_id&kind=eq.support&recipient_role=eq.admin&is_read=eq.false&limit=1000');notices.forEach(n=>unread.set(n.entity_id,(unread.get(n.entity_id)||0)+1))}catch{}
try{const recent=await api('wholesale_support_messages','select=id,sender_id,created_at&created_at=gte.'+encodeURIComponent(new Date(Date.now()-86400000).toISOString())+'&order=created_at.desc&limit=300');if(messagesPrimed)recent.forEach(m=>{if(m.sender_id!==user()?.id&&!seenMessages.has(m.id))sound('رسالة دعم جديدة','وصلت رسالة من نشاط تجاري','support-'+m.id)});seenMessages=new Set(recent.map(m=>m.id));messagesPrimed=true}catch{}
const ids=[...new Set(rows.map(t=>t.merchant_id).filter(Boolean))],profiles=ids.length?await api('wholesale_profiles','select=id,full_name,business_name&id=in.('+ids.join(',')+')'):[],names=new Map(profiles.map(p=>[p.id,p.business_name||p.full_name]));list.replaceChildren();const unreadTotal=[...unread.values()].reduce((a,b)=>a+b,0);count.textContent=rows.length+' محادثة • '+unreadTotal+' رسائل غير مقروءة';if(!rows.length){list.append(el('p','','لا توجد محادثات دعم حالياً'));return}rows.forEach(t=>{const row=el('article','df-ticket-row'),d=el('div',''),n=unread.get(t.order_id||t.id)||0;d.append(el('b','',names.get(t.merchant_id)||'نشاط تجاري'),el('p','',t.subject||'دردشة دعم'),el('small','','أُنشئت: '+date(t.created_at)+' • آخر تحديث: '+date(t.last_merchant_reply_at||t.last_admin_reply_at||t.created_at)),el('small','df-open-state',(t.admin_opened_at||localStorage.getItem('df-opened-'+t.id))?'فُتحت: '+date(t.admin_opened_at||localStorage.getItem('df-opened-'+t.id)):'لم تُفتح بعد'));if(n)d.append(el('strong','df-unread-badge',n+' رسالة جديدة'));const b=el('button','','فتح المحادثة');b.onclick=()=>openChat(t,names.get(t.merchant_id)||'النشاط التجاري');row.append(d,b);list.append(row)})}
function supportPage(){const page=$('.admin-support-page');if(!page)return;$('#df-admin-chat-button')?.remove();let box=$('#df-support-inbox',page);if(!box){box=el('section','df-support-inbox');box.id='df-support-inbox';const h=el('header','');h.append(el('h2','','دردشات الأنشطة التجارية'),el('span','df-ticket-count','جارِ التحميل'));box.append(h,el('div','df-ticket-list'));page.append(box)}if(box.dataset.started)return;box.dataset.started='1';const update=()=>tickets($('.df-ticket-list',box),$('.df-ticket-count',box)).catch(e=>$('.df-ticket-count',box).textContent=e.message);update();if(ticketPoll)clearInterval(ticketPoll);ticketPoll=setInterval(()=>{if($('.admin-support-page'))update()},5000)}
function traders(){const page=$('.admin .users-management'),cards=$('.admin-cards',page);if(!page||!cards)return;if(!$('#df-trader-search',page)){const bar=el('div','df-trader-filter'),input=el('input');input.id='df-trader-search';input.placeholder='بحث بالاسم أو النشاط أو الهاتف';const select=document.createElement('select');[['all','كل المستخدمين'],['تاجر','التجار فقط'],['مشرف','المشرفون فقط']].forEach(([v,l])=>{const o=document.createElement('option');o.value=v;o.textContent=l;select.append(o)});bar.append(input,select);cards.before(bar);const filter=()=>$$(':scope>article',cards).forEach(c=>c.hidden=!c.innerText.toLowerCase().includes(input.value.trim().toLowerCase())||(select.value!=='all'&&!c.innerText.includes(select.value)));input.oninput=filter;select.onchange=filter}
$$('.admin-cards>article:not(.df-bound)',cards).forEach(card=>{card.classList.add('df-bound');card.tabIndex=0;card.setAttribute('role','button');card.setAttribute('aria-label','عرض تفاصيل '+($('h3',card)?.textContent||'النشاط التجاري'));const open=()=>traderProfile(card).catch(x=>alert(x.message));card.addEventListener('click',e=>{if(e.target.closest('button,a'))return;open()});card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open()}})})}
async function allRows(path,columns,query=''){const result=[];const size=1000;for(let offset=0;;offset+=size){const params='select='+columns+(query?'&'+query:'')+'&order=id.asc&limit='+size+'&offset='+offset;const batch=await api(path,params);result.push(...batch);if(batch.length<size)break}return result}
let balancesPoll=null;
async function unpaidAccounts(){
  const page=$('.admin-content'),active=$('.admin-header nav button.active');
  if(!page||!active?.textContent.includes('الحسابات')){if(balancesPoll){clearInterval(balancesPoll);balancesPoll=null}$('#df-unpaid-accounts')?.remove();return}
  let panel=$('#df-unpaid-accounts');
  if(!panel){panel=el('section','df-unpaid-accounts');panel.id='df-unpaid-accounts';const summary=$('.accounts-summary',page);(summary||$('.admin-welcome',page))?.after(panel)}
  if(!panel||panel.dataset.loading==='1'||Date.now()-Number(panel.dataset.lastLoaded||0)<30000)return;
  panel.dataset.loading='1';
  try{
    const [profiles,transactions]=await Promise.all([allRows('wholesale_profiles','id,full_name,business_name,phone,role,created_at'),allRows('wholesale_transactions','id,merchant_id,amount')]);
    if(!panel.isConnected||!$('.admin-header nav button.active')?.textContent.includes('الحسابات'))return;
    const totals=new Map();transactions.forEach(t=>totals.set(t.merchant_id,(totals.get(t.merchant_id)||0)+Number(t.amount||0)));
    const outstanding=profiles.filter(p=>p.role!=='admin').map(p=>({p,amount:Math.max(0,totals.get(p.id)||0)})).filter(x=>x.amount>0.009).sort((a,b)=>b.amount-a.amount);
    const header=el('header',''),heading=el('div','');heading.append(el('h2','','الحسابات غير المسددة'),el('small','',outstanding.length+' نشاط تجاري'));header.append(heading,el('strong','',cash(outstanding.reduce((n,x)=>n+x.amount,0))));panel.replaceChildren(header);
    if(!outstanding.length)panel.append(el('p','df-unpaid-empty','ماكو مبالغ غير مسددة حالياً'));
    else{const list=el('div','df-unpaid-list');outstanding.forEach(({p,amount})=>{const name=p.business_name||p.full_name||'نشاط تجاري',row=el('article','df-unpaid-row'),avatar=el('span','df-unpaid-avatar',name.trim().charAt(0)||'ت'),identity=el('div','df-unpaid-identity');identity.append(el('b','',name));if(p.full_name&&p.full_name!==name)identity.append(el('small','',p.full_name));if(p.phone){const phone=el('small','',p.phone);phone.dir='ltr';identity.append(phone)}const due=el('div','df-unpaid-amount');due.append(el('small','','المبلغ غير المسدد'),el('strong','',cash(amount)));const open=el('button','df-open-trader','عرض الملف');open.type='button';open.setAttribute('aria-label','عرض الملف الشخصي لـ '+name);open.onclick=()=>traderProfileById(p.id,p).catch(e=>alert(e.message));row.append(avatar,identity,due,open);list.append(row)});panel.append(list)}
  }catch(e){if(panel.isConnected)panel.replaceChildren(el('p','df-unpaid-error','تعذر تحميل الأرصدة: '+e.message))}finally{panel.dataset.loading='0';panel.dataset.lastLoaded=String(Date.now())}
  if(!balancesPoll)balancesPoll=setInterval(unpaidAccounts,60000)
}
async function traderProfile(card){const phone=$$('p',card).find(x=>x.dir==='ltr')?.textContent.trim(),name=$('h3',card)?.textContent||'',all=await api('wholesale_profiles','select=id,full_name,business_name,phone,created_at&phone=eq.'+encodeURIComponent(phone)+'&limit=20'),p=all.find(x=>x.business_name===name||x.full_name===name)||all[0];if(!p)throw Error('تعذر تحديد حساب التاجر');return traderProfileById(p.id,p)}
async function traderProfileById(id,profile){
  const p=profile||((await api('wholesale_profiles','select=id,full_name,business_name,phone,created_at&id=eq.'+encodeURIComponent(id)+'&limit=1'))[0]);
  if(!p)throw Error('تعذر تحديد حساب التاجر');
  const merchantId=encodeURIComponent(p.id),[orders,tx]=await Promise.all([allRows('wholesale_orders','id,status','merchant_id=eq.'+merchantId),allRows('wholesale_transactions','id,amount,title,kind,created_at','merchant_id=eq.'+merchantId)]);
  const delivered=orders.filter(o=>o.status==='تم التوصيل').length,returned=orders.filter(o=>['راجع','مرتجع','مرتجعة','مرفوض'].includes(o.status)).length,balance=Math.max(0,tx.reduce((a,t)=>a+Number(t.amount||0),0)),name=p.business_name||p.full_name||'نشاط تجاري';
  let backdrop=$('#df-trader-backdrop');if(!backdrop){backdrop=el('div','df-trader-backdrop');backdrop.id='df-trader-backdrop';document.body.append(backdrop);backdrop.addEventListener('click',e=>{if(e.target===backdrop)backdrop.remove()})}
  const pane=el('section','df-trader-profile');pane.setAttribute('role','dialog');pane.setAttribute('aria-modal','true');pane.setAttribute('aria-label','تفاصيل '+name);const h=el('header',''),title=el('div','');title.append(el('small','','الملف الشخصي والمالي'),el('h2','',name));const x=el('button','','إغلاق ×');x.type='button';x.onclick=()=>backdrop.remove();h.append(title,x);pane.append(h);
  const contact=el('div','df-trader-contact');if(p.full_name)contact.append(el('span','',p.full_name));if(p.phone){const phone=el('span','',p.phone);phone.dir='ltr';contact.append(phone)}pane.append(contact);
  const stats=el('div','df-trader-stats');[['كل الطلبات',orders.length],['الواصل',delivered],['الراجع',returned],['غير المسدد',cash(balance)],['تاريخ الانضمام',date(p.created_at)]].forEach(v=>{const a=el('article','');a.append(el('small','',v[0]),el('b','',v[1]));stats.append(a)});pane.append(stats,el('h3','','المعاملات المالية'));
  const list=el('div','df-trader-transactions');if(!tx.length)list.append(el('p','','لا توجد معاملات مالية مسجلة'));tx.sort((a,b)=>new Date(b.created_at||0)-new Date(a.created_at||0)).slice(0,150).forEach(t=>{const r=el('div','df-transaction');r.append(el('span','',t.title||t.kind||'معاملة'),el('time','',date(t.created_at)),el('b','',cash(t.amount)));list.append(r)});pane.append(list);backdrop.replaceChildren(pane);x.focus();document.addEventListener('keydown',function esc(e){if(e.key==='Escape'&&$('#df-trader-backdrop')){backdrop.remove();document.removeEventListener('keydown',esc)}})
}
function cardsAfter(card,pane){const c=card.closest('.admin-cards');c.after(pane)}
const ORDER_STATES=['قيد الانتظار','قيد التجهيز','قيد التوصيل','تم التوصيل','سيجهز غداً','تم الاتصال لا يرد','الزبون طلب التأجيل','تم تأجيل الطلب لأنه أطراف','تحويل إلى غير محافظة','رقم الزبون خطأ','رقم الهاتف مغلق','مرفوض'];
let selectedOrderStatus='all';
function orderFilter(){
  const page=$('.admin .admin-table.admin-full');
  if(!page||!$('.admin-header nav button.active')?.textContent.includes('الطلبات')){$('#df-order-status-filter')?.remove();return}
  let bar=$('#df-order-status-filter');
  if(!bar){bar=el('div','df-order-filter');bar.id='df-order-status-filter';const label=el('label','','حالة الطلب'),select=el('select');select.id='df-order-status-select';select.setAttribute('aria-label','فلترة الطلبات حسب الحالة');label.append(select);bar.append(label,el('span','df-order-filter-count'));page.before(bar);select.onchange=()=>{selectedOrderStatus=select.value;filter()}}
  const cards=$$('article',page).filter(card=>!card.classList.contains('empty-inline'));
  const counts=new Map();cards.forEach(card=>{const status=$('.badge',card)?.textContent.trim();if(status)counts.set(status,(counts.get(status)||0)+1)});
  if(selectedOrderStatus!=='all'&&!counts.has(selectedOrderStatus))counts.set(selectedOrderStatus,0);
  const states=[...counts.keys()].sort((a,b)=>{const ia=ORDER_STATES.indexOf(a),ib=ORDER_STATES.indexOf(b);return(ia<0?999:ia)-(ib<0?999:ib)||a.localeCompare(b,'ar')});
  const signature=JSON.stringify([cards.length,[...counts]]);
  const select=$('#df-order-status-select',bar);
  if(bar.dataset.options!==signature){select.replaceChildren(new Option('كل الحالات ('+cards.length+')','all'),...states.map(state=>new Option(state+' ('+counts.get(state)+')',state)));select.value=selectedOrderStatus;bar.dataset.options=signature}
  function filter(){let visible=0;cards.forEach(card=>{const status=$('.badge',card)?.textContent.trim();card.hidden=selectedOrderStatus!=='all'&&status!==selectedOrderStatus;if(!card.hidden)visible++});const count=$('.df-order-filter-count',bar),label=visible+' من '+cards.length+' طلب';if(count.textContent!==label)count.textContent=label}
  filter()
}
function statusSheet(){const sheet=$('.admin .admin-detail-sheet');if(!sheet||sheet.dataset.dfStatusBound)return;const btn=$$('.admin-order-actions button',sheet).find(x=>x.textContent.includes('تغيير الحالة'));if(!btn)return;sheet.dataset.dfStatusBound='1';btn.onclick=e=>{e.stopPropagation();if($('#df-status-picker',sheet))return;const number=$('header h2',sheet)?.textContent.trim().replace(/^الطلب\s*/,'');const wrap=el('div','df-status-picker');wrap.id='df-status-picker';wrap.append(el('strong','','اختر الحالة الجديدة'));const select=document.createElement('select');select.append(new Option('اختر حالة الطلب',''));ORDER_STATES.forEach(s=>select.append(new Option(s,s)));select.onchange=async()=>{if(!select.value||!number)return;select.disabled=true;try{await api('wholesale_orders','order_number=eq.'+encodeURIComponent(number),'PATCH',{status:select.value,status_changed_at:new Date().toISOString()});location.reload()}catch(e){select.disabled=false;alert(e.message)}};wrap.append(select);sheet.querySelector('.admin-order-actions').after(wrap)}}
function orderTools(){const page=$('.admin .admin-table.admin-full');if(!page)return;$$('.admin-table.admin-full>article:not(.df-actions-added)',page).forEach(card=>{if(card.classList.contains('empty-inline'))return;const id=card.innerText.match(/DF-[\w-]+/)?.[0];if(!id)return;card.classList.add('df-actions-added');const tools=el('div','df-order-tools'),edit=el('button','','تعديل'),del=el('button','','حذف'),status=document.createElement('select');[['','تغيير الحالة'],...ORDER_STATES.map(x=>[x,x])].forEach(([v,l])=>{const o=document.createElement('option');o.value=v;o.textContent=l;status.append(o)});['pointerdown','mousedown','click','keydown'].forEach(name=>status.addEventListener(name,e=>e.stopPropagation()));status.setAttribute('aria-label','تغيير حالة الطلب '+id);
edit.onclick=async e=>{e.stopPropagation();const customer=prompt('اسم الزبون');if(customer===null)return;const phone=prompt('هاتف الزبون');if(phone===null)return;const price=prompt('سعر البيع المتفق عليه');if(price===null)return;try{await api('wholesale_orders','order_number=eq.'+encodeURIComponent(id),'PATCH',{customer_name:customer,customer_phone:phone,customer_price:Number(price)});location.reload()}catch(x){alert(x.message)}};
del.onclick=async e=>{e.stopPropagation();if(!confirm('حذف الطلب '+id+' نهائياً؟'))return;try{await api('wholesale_orders','order_number=eq.'+encodeURIComponent(id),'DELETE');location.reload()}catch(x){alert(x.message)}};
status.onchange=async e=>{e.stopPropagation();if(!status.value)return;try{await api('wholesale_orders','order_number=eq.'+encodeURIComponent(id),'PATCH',{status:status.value,status_changed_at:new Date().toISOString()});location.reload()}catch(x){alert(x.message)}};
tools.append(edit,del,status);card.append(tools)})}
function restrictCreate(){const nav=$('.admin-header nav'),active=nav&&($('button[aria-current="page"]',nav)||$('button.active',nav)||$('button[data-active="true"]',nav));if(!active)return;const label=(active.getAttribute('aria-label')||active.textContent||'').trim();const home=/الرئيسية|الرئيس|home/i.test(label),orders=/الطلبات|طلباتي|orders/i.test(label),ok=home||orders;$$('.admin .admin-welcome .main-btn,.admin .main-btn[data-create-order]').forEach(b=>{b.hidden=!ok})}

let merchantWatch=null,merchantSignature=null,merchantWatchUser=null,merchantReloading=false;
async function watchMerchantData(){const u=user();if(!u?.id||role()==='admin'){if(merchantWatch){clearInterval(merchantWatch);merchantWatch=null}merchantWatchUser=null;merchantSignature=null;return}if(merchantWatchUser!==u.id){if(merchantWatch)clearInterval(merchantWatch);merchantWatchUser=u.id;merchantSignature=null;const refresh=async()=>{try{const id=encodeURIComponent(u.id),[orders,tx]=await Promise.all([api('wholesale_orders','select=id,status,status_changed_at,updated_at&merchant_id=eq.'+id+'&order=updated_at.desc&limit=500'),api('wholesale_transactions','select=id,amount,created_at&merchant_id=eq.'+id+'&order=created_at.desc&limit=500')]);const signature=JSON.stringify([orders.map(o=>[o.id,o.status,o.status_changed_at,o.updated_at]),tx.map(t=>[t.id,t.amount,t.created_at])]);if(merchantSignature!==null&&signature!==merchantSignature&&!merchantReloading){merchantReloading=true;location.reload();return}merchantSignature=signature}catch{}};refresh();merchantWatch=setInterval(refresh,15000)}}

let scheduled=false;function scan(){scheduled=false;if(!session()?.access_token){if(ticketPoll)clearInterval(ticketPoll);ticketPoll=null;return}if($('.admin')){soundButtons();pushButton();supportPage();traders();orderTools();orderFilter();statusSheet();unpaidAccounts();restrictCreate()}if($('.merchant-app .header-actions'))merchantNotificationControls();if($('.merchant-app .ledger'))pendingPayments();watchMerchantData()}
new MutationObserver(()=>{if(!scheduled){scheduled=true;requestAnimationFrame(scan)}}).observe(document.documentElement,{childList:true,subtree:true,attributes:true,attributeFilter:['class']});
document.addEventListener('click',e=>{if(e.target.closest('.admin-header nav button'))setTimeout(scan,80)});startPoll();scan();window.addEventListener('storage',startPoll);
})();
